// src/types/wrestlers.ts
export const wrestlers = [
    // 1980s-1990s Legends
    "Hulk Hogan",
    "Macho Man Randy Savage",
    "Ultimate Warrior",
    "Andre The Giant",
    "Big John Studd",
    "Ted DiBiase",
    "Jake The Snake Roberts",
    "Bret Hart",
    "Shawn Michaels",
    "Diesel",
    "Razor Ramon",
    "Lex Luger",
    "Ric Flair",
    "Roddy Piper",
    "Mr. Perfect",
    "The Undertaker",
    "Yokozuna",
    "Owen Hart",
    "The British Bulldog",
    "Sid Justice",
    "Sgt. Slaughter",
    "Rick Rude",
    "Doink The Clown",
    "Papa Shango",
    "The Big Boss Man",
    "Earthquake",
    "Typhoon",
    "The Barbarian",
    "Haku",
    "Tatanka",
    "Jeff Jarrett",
    "1-2-3 Kid",
    "Bob Backlund",
    "King Kong Bundy",
    "Kamala",
    "Jim Duggan",
    "The Rockers (Marty Jannetty & Shawn Michaels)",
    "The Bushwhackers",
    "The Headshrinkers",
    "Demolition (Ax & Smash)",
    "The Legion of Doom",
    "The Nasty Boys",
    "Rikishi",
    "The Godfather",
    "Val Venis",
    "Al Snow",
    
    // Attitude Era & Ruthless Aggression
    "The Rock",
    "Stone Cold Steve Austin",
    "Triple H",
    "Kurt Angle",
    "Chris Jericho",
    "Edge",
    "Christian",
    "Matt Hardy",
    "Jeff Hardy",
    "Kane",
    "Big Show",
    "Brock Lesnar",
    "Goldberg",
    "Rob Van Dam",
    "Booker T",
    "Eddie Guerrero",
    "Rey Mysterio",
    "Chris Benoit",
    "Test",
    "Lance Storm",
    "William Regal",
    "Scott Steiner",
    "Batista",
    "John Cena",
    "Randy Orton",
    "JBL",
    "Carlito",
    "Shelton Benjamin",
    "MVP",
    "Umaga",
    "Finlay",
    "Hornswoggle",
    "The Boogeyman",
    "Eugene",
    "Chavo Guerrero",
    "Jamie Noble",
    "Hardcore Holly",
    "Paul London",
    "Brian Kendrick",
    "Bobby Lashley",
    "The Great Khali",
    "Mr. Kennedy",
    "Vladimir Kozlov",
    
    // PG Era & Modern Superstars
    "CM Punk",
    "Daniel Bryan",
    "Sheamus",
    "Wade Barrett",
    "Drew McIntyre",
    "The Miz",
    "John Morrison",
    "Cody Rhodes",
    "Ted DiBiase Jr.",
    "Damien Sandow",
    "Ryback",
    "Kofi Kingston",
    "Big E",
    "Xavier Woods",
    "Rusev",
    "Bray Wyatt",
    "Luke Harper",
    "Erick Rowan",
    "Dean Ambrose",
    "Seth Rollins",
    "Roman Reigns",
    "Braun Strowman",
    "Sami Zayn",
    "Kevin Owens",
    "Shinsuke Nakamura",
    "AJ Styles",
    "Finn Balor",
    "Samoa Joe",
    "Baron Corbin",
    "Chad Gable",
    "Otis",
    "Aleister Black",
    "Ricochet",
    "Andrade",
    "Bobby Roode",
    "Dolph Ziggler",
    "Robert Roode",
    "Keith Lee",
    "Karrion Kross",
    "Johnny Gargano",
    "Tommaso Ciampa",
    "Pete Dunne",
    "LA Knight",
    
    // Current Superstars & Future Stars
    "Logan Paul",
    "Gunther",
    "Solo Sikoa",
    "Dominik Mysterio",
    "Austin Theory",
    "Carmelo Hayes",
    "Bron Breakker",
    "Grayson Waller",
    "Ilja Dragunov",
    "Santos Escobar",
    "Dragon Lee",
    "Jey Uso",
    "Jimmy Uso",
    "Seth Rollins",
    "Drew McIntyre",
    "Damian Priest",
    "Rey Mysterio",
    "LA Knight",
    "Karrion Kross",
    "JD McDonagh",
    "Omos",
    
    // Surprise Entrants & Guest Appearances
    "Shane McMahon",
    "Vince McMahon",
    "Pat McAfee",
    "Bad Bunny",
    "Johnny Knoxville",
    "Michael Cole",
    "JBL",
    "Jerry Lawler",
    "Tazz",
    "The Hurricane",
    "Booker T",
    "RVD",
    "Carlito",
    "DDP",
    "Kevin Nash",
    "Scott Hall",
    "Road Dogg",
    "Billy Gunn",
    "X-Pac",
    "The Dudley Boyz",
    "Jake Roberts",
    "The Honky Tonk Man",
    "Titus O’Neil",
    "The Mountie",
    "IRS",
    "Bob Orton",
    "Ted DiBiase Sr.",
    "Ric Flair",
    "Sting",
    "The Ultimate Warrior (RIP)",
  ];
  